name: ci

on:
  push:
    tags:
      - '*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: tritonsio/k8s-tools
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
      - name: Docker meta humans
        id: meta-humans
        uses: docker/metadata-action@v3
        with:
          images: tritonsio/k8s-tools
          tags: |
            type=semver,pattern={{version}}-humans
            type=semver,pattern={{major}}.{{minor}}-humans
            type=semver,pattern={{major}}-humans
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push humans
        uses: docker/build-push-action@v4
        with:
          cache-from: type=registry,ref=tritonsio/k8s-tools:latest
          push: true
          tags: ${{ steps.meta-humans.outputs.tags }}
          labels: ${{ steps.meta-humans.outputs.labels }}
          target: humans
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          cache-from: type=registry,ref=tritonsio/k8s-tools:latest
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          target: release
